services:
  - type: web
    name: xchat-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn simple_app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: APP_NAME
        value: Xchat API
      - key: DEBUG
        value: false