services:
  - type: web
    name: xchat-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash smart_start.sh
    plan: free
    envVars:
      - key: APP_NAME
        value: Xchat API
      - key: DEBUG
        value: false