services:
  - type: web
    name: xchat-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 run_server.py
    plan: free
    envVars:
      - key: APP_NAME
        value: Xchat API
      - key: DEBUG
        value: false